// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cebruyycvufpfftewktd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlYnJ1eXljdnVmcGZmdGV3a3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NTY1NTIsImV4cCI6MjA3NzEzMjU1Mn0.buZPLfB3BE4fzCyuUFyryrEEy9ya08mOxikSFyraiL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});